// @flow

export const CONFIRM_SELECTION = 'CONFIRM_SELECTION';
export const DELETE_SELECTION = 'DELETE_SELECTION';
export const SET_SELECTED_GROUP = 'SET_SELECTED_GROUP';
export const SET_ITEM = 'SET_ITEM';
export const SET_MODIFIER_GROUP = 'SET_MODIFIER_GROUP';
export const SET_MODIFIER = 'SET_MODIFIER';
export const ITEM_NAV_BACK = 'ITEM_NAV_BACK';
export const ITEM_NAV_FWD = 'ITEM_NAV_FWD';
export const UNDO_LAST_MOD = 'UNDO_LAST_MOD';